import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    fi: {
        tervetuloa: "KURSSITENTIT - TERVETULOA",
        kirjaudu: "Kirjaudu sähköpostiosoitteella",
        sähköposti: "Sähköposti:",
        lähetä: "Lähetä",
        rekisteröidy: "Rekisteröidy",
        rekisteröimätön: "Sähköpostia ei ole vielä rekisteröity käyttäjätiliksi?",
        luo: "Luo tili",
        etunimi: "Etunimi:",
        sukunimi: "Sukunimi:",
        salasana: "Salasana:",
        sähköpostimuoto: "Tarkista sähköpostiosoite!",
        salasanamuoto: "Salasana on vähintään 6 merkkiä, joista yksi numero, yksi suuraakkonen, yksi pieni kirjain!",
        uudelleen: "Salasana uudelleen:",
        opettaja: "Olen opettaja:",
        paluu: "Paluu",
        peruuta: "Peruuta",
        tpoisto: "Tentin poisto?",
        tvahvistus: "Poistetaanko kurssilta tentti: ",
        kpoisto: "Kysymyksen poisto?",
        kvahvistus: "Poistetaanko tentiltä kysymys: ",
        vpoisto: "Vaihtoehdon poisto?",
        vvahvistus: "Poistetaanko kysymykseltä vaihtoehto :",
        kurssit: "KURSSIT",
        tentit: "TENTIT",
        tietoa: "TIETOA SOVELLUKSESTA",
        tohje: "(kaksoisklikkaus/ESC = kokoruutu/pikkukuva)",
        poistu: "POISTU",
        kurssivalinta: "KURSSIVALINTA:",
        tenttivalinta: "TENTTIVALINTA (ei valittua kurssia, kaikki tentit):",
        minimi: "minimi",
        kurssi: "KURSSI:",
        oikeat: "Oikeat",
        kaaviot: "Kaaviot",
        jakauma: "Pistejakauma aihealueittain",
        aluepisteet: "Aihealuiden pisteet",
        gotsikot: ['kriminologia', 'scientologia', 'psykologia', 'ornitologia']
    },
    en: {
        tervetuloa: "COURCES AND EXAMS - WELLCOME",
        kirjaudu: "Login with email",
        sähköposti: "Email:",
        lähetä: "Send",
        rekisteröidy: "Register",
        rekisteröimätön: "Email has not been registered yet?",
        luo: "Register",
        etunimi: "Fistname:",
        sukunimi: "Lastname:",
        salasana: "Password:",
        sähköpostimuoto: "Check the email address!",
        salasanamuoto: "Password must be at least 6 characters, including one number, one captical and one lower case!",
        uudelleen: "Password again:",
        opettaja: "I am a teacher:",
        paluu: "Back",
        peruuta: "Cancel",
        tpoisto: "Remove this exam?",
        tvahvistus: "Remove from this course the exam: ",
        kpoisto: "Remove this question?",
        kvahvistus: "Remove from this exam the question: ",
        vpoisto: "Remove this choice?",
        vvahvistus: "Remove from this question the choice: ",
        kurssit: "COURCES",
        tentit: "EXAMS",
        tietoa: "ABOUT C&E ",
        tohje: "(doubleclick/ESC = fullscreen/back)",
        poistu: "SIGN OUT",
        kurssivalinta: "CHOOSE COURCE:",
        tenttivalinta: "CHOOSE EXAM (cource not chosen, all exams):",
        minimi: "minimum",
        kurssi: "COURCE:",
        oikeat: "Right ones",
        kaaviot: "Charts",
        jakauma: "Distribution of points by subject",
        aluepisteet: "Points per subject",
        gotsikot: ['criminology', 'scientology', 'psychology', 'ornithology']
    }
})

export default strings