import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    fi: {
        tervetuloa: "KURSSITENTIT - TERVETULOA",
        kirjaudu: "Kirjaudu sähköpostiosoitteella",
        sähköposti: "Sähköposti:",
        salasana: "Salasana kurssitentteihin:",
        lähetä: "Lähetä",
        rekisteröidy: "Rekisteröidy",
        rekisteröimätön: "Sähköpostia ei ole vielä rekisteröity käyttäjätiliksi?",
        luo: "Luo tili",
        etunimi: "Etunimi:",
        sukunimi: "Sukunimi:",
        salasana: "Salasana:",
        uudelleen: "Salasana uudelleen:",
        opettaja: "Olen opettaja:",
        paluu: "Paluu",
        peruuta: "Peruuta",
        tpoisto: "Tentin poisto?",
        tvahvistus: "Poistetaanko kurssilta tentti: ",
        kpoisto: "Kysymyksen poisto?",
        kvahvistus: "Poistetaanko tentiltä kysymys: ",
        vpoisto: "Vaihtoehdon poisto?",
        vvahvistus: "Poistetaanko kysymykseltä vaihtoehto :",
        kurssit: "KURSSIT",
        tentit: "TENTIT",
        tietoa: "TIETOA SOVELLUKSESTA",
        poistu: "POISTU",
        kurssivalinta: "KURSSIVALINTA:",
        tenttivalinta: "TENTTIVALINTA:",
        minimi: "minimi",
        kurssi: "KURSSI:",
        oikeat: "Oikeat",
        kaaviot: "Kaaviot",
        jakauma: "Pistejakauma aihealueittain",
        aluepisteet: "Aihealuiden pisteet",
        gotsikot: ['kriminologia', 'scientologia', 'psykologia', 'ornitologia']
    },
    en: {
        tervetuloa: "COURCES AND EXAMS - WELLCOME",
        kirjaudu: "Login with email",
        sähköposti: "Email:",
        salasana: "Password for Cources And Exams:",
        lähetä: "Send",
        rekisteröidy: "Register",
        rekisteröimätön: "Email has not been registered yet?",
        luo: "Register",
        etunimi: "Fistname:",
        sukunimi: "Lastname:",
        salasana: "Password:",
        uudelleen: "Password again:",
        opettaja: "I am a teacher:",
        paluu: "Back",
        peruuta: "Cancel",
        tpoisto: "Remove this exam?",
        tvahvistus: "Remove from this course the exam: ",
        kpoisto: "Remove this question?",
        kvahvistus: "Remove from this exam the question: ",
        vpoisto: "Remove this choice?",
        vvahvistus: "Remove from this question the choice: ",
        kurssit: "COURCES",
        tentit: "EXAMS",
        tietoa: "ABOUT C&E ",
        poistu: "SIGN OUT",
        kurssivalinta: "CHOOSE COURCE:",
        tenttivalinta: "CHOOSE EXAM:",
        minimi: "minimum",
        kurssi: "COURCE:",
        oikeat: "Right ones",
        kaaviot: "Charts",
        jakauma: "Distribution of points by subject",
        aluepisteet: "Points per subject",
        gotsikot: ['criminology', 'scientology', 'psychology', 'ornithology']
    }
})

export default strings